/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeLoginRouteImport } from './routes/employee-login'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffInviteTokenRouteImport } from './routes/staff-invite.$token'
import { Route as ShadowIdRouteImport } from './routes/shadow.$id'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as HiredIdRouteImport } from './routes/hired.$id'
import { Route as InterviewIdHostRouteImport } from './routes/interview.$id.host'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/employee-login',
  path: '/employee-login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInviteTokenRoute = StaffInviteTokenRouteImport.update({
  id: '/staff-invite/$token',
  path: '/staff-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowIdRoute = ShadowIdRouteImport.update({
  id: '/shadow/$id',
  path: '/shadow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HiredIdRoute = HiredIdRouteImport.update({
  id: '/hired/$id',
  path: '/hired/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdHostRoute = InterviewIdHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => InterviewIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/employee': typeof EmployeeRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/signup': typeof SignupRoute
  '/hired/$id': typeof HiredIdRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/join/$slug': typeof JoinSlugRoute
  '/shadow/$id': typeof ShadowIdRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/interview/$id/host': typeof InterviewIdHostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/employee': typeof EmployeeRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/signup': typeof SignupRoute
  '/hired/$id': typeof HiredIdRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/join/$slug': typeof JoinSlugRoute
  '/shadow/$id': typeof ShadowIdRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/interview/$id/host': typeof InterviewIdHostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/employee': typeof EmployeeRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/signup': typeof SignupRoute
  '/hired/$id': typeof HiredIdRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/join/$slug': typeof JoinSlugRoute
  '/shadow/$id': typeof ShadowIdRoute
  '/staff-invite/$token': typeof StaffInviteTokenRoute
  '/interview/$id/host': typeof InterviewIdHostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/careers'
    | '/employee'
    | '/employee-login'
    | '/login'
    | '/manager'
    | '/signup'
    | '/hired/$id'
    | '/interview/$id'
    | '/join/$slug'
    | '/shadow/$id'
    | '/staff-invite/$token'
    | '/interview/$id/host'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/careers'
    | '/employee'
    | '/employee-login'
    | '/login'
    | '/manager'
    | '/signup'
    | '/hired/$id'
    | '/interview/$id'
    | '/join/$slug'
    | '/shadow/$id'
    | '/staff-invite/$token'
    | '/interview/$id/host'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/careers'
    | '/employee'
    | '/employee-login'
    | '/login'
    | '/manager'
    | '/signup'
    | '/hired/$id'
    | '/interview/$id'
    | '/join/$slug'
    | '/shadow/$id'
    | '/staff-invite/$token'
    | '/interview/$id/host'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  EmployeeRoute: typeof EmployeeRoute
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  SignupRoute: typeof SignupRoute
  HiredIdRoute: typeof HiredIdRoute
  InterviewIdRoute: typeof InterviewIdRouteWithChildren
  JoinSlugRoute: typeof JoinSlugRoute
  ShadowIdRoute: typeof ShadowIdRoute
  StaffInviteTokenRoute: typeof StaffInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-login': {
      id: '/employee-login'
      path: '/employee-login'
      fullPath: '/employee-login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-invite/$token': {
      id: '/staff-invite/$token'
      path: '/staff-invite/$token'
      fullPath: '/staff-invite/$token'
      preLoaderRoute: typeof StaffInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow/$id': {
      id: '/shadow/$id'
      path: '/shadow/$id'
      fullPath: '/shadow/$id'
      preLoaderRoute: typeof ShadowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hired/$id': {
      id: '/hired/$id'
      path: '/hired/$id'
      fullPath: '/hired/$id'
      preLoaderRoute: typeof HiredIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id/host': {
      id: '/interview/$id/host'
      path: '/host'
      fullPath: '/interview/$id/host'
      preLoaderRoute: typeof InterviewIdHostRouteImport
      parentRoute: typeof InterviewIdRoute
    }
  }
}

interface InterviewIdRouteChildren {
  InterviewIdHostRoute: typeof InterviewIdHostRoute
}

const InterviewIdRouteChildren: InterviewIdRouteChildren = {
  InterviewIdHostRoute: InterviewIdHostRoute,
}

const InterviewIdRouteWithChildren = InterviewIdRoute._addFileChildren(
  InterviewIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  EmployeeRoute: EmployeeRoute,
  EmployeeLoginRoute: EmployeeLoginRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  SignupRoute: SignupRoute,
  HiredIdRoute: HiredIdRoute,
  InterviewIdRoute: InterviewIdRouteWithChildren,
  JoinSlugRoute: JoinSlugRoute,
  ShadowIdRoute: ShadowIdRoute,
  StaffInviteTokenRoute: StaffInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
